# Generated by Django 2.0.1 on 2018-01-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summoners',
            old_name='pub_date',
            new_name='modify_date',
        ),
    ]
